# Generated by Django 6.1 on 2026-08-16 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='autor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (opcional)'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='autor_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de quien pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.TextField(verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Respondida por'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.TextField(blank=True, help_text='Escribí acá la respuesta y guardá. Se va a publicar automáticamente en la web.', null=True, verbose_name='Tu respuesta'),
        ),
    ]
