# Generated by Django 6.1 on 2026-09-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=10, verbose_name='Nivel')),
                ('categoria', models.CharField(choices=[('pregunta_nueva', 'Pregunta recibida'), ('pregunta_rechazada', 'Pregunta rechazada por moderación'), ('limite_envios', 'Envío bloqueado por límite'), ('evento_nuevo', 'Evento cargado'), ('suscripcion', 'Suscripción a eventos'), ('email', 'Envío de email'), ('otro', 'Otro')], db_index=True, default='otro', max_length=30, verbose_name='Categoría')),
                ('mensaje', models.TextField(verbose_name='Detalle')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='Navegador / dispositivo')),
                ('usuario', models.CharField(blank=True, max_length=150, verbose_name='Cuenta del staff')),
            ],
            options={
                'verbose_name': 'Registro del sistema',
                'verbose_name_plural': 'Registros del sistema',
                'ordering': ['-fecha'],
            },
        ),
    ]
